// === DAILY QUOTE WIDGET ===
document.addEventListener("DOMContentLoaded", () => {
  const quoteText = document.getElementById("quote-text");

  if (!quoteText) {
    console.error("❌ Elemento #quote-text não encontrado!");
    return;
  }

  const quotes = [
  "Code is like humor. When you have to explain it, it’s bad.",
  "Talk is cheap. Show me the code.",
  "Programs must be written for people to read, and only incidentally for machines to execute.",
  "First, solve the problem. Then, write the code.",
  "Simplicity is the soul of efficiency.",
  "Before software can be reusable, it first has to be usable.",
  "The best error message is the one that never shows up.",
  "Clean code always looks like it was written by someone who cares.",
  "Don’t comment bad code — rewrite it.",
  "Experience is the name everyone gives to their mistakes.",
  "Programming is the art of algorithm design and the craft of debugging errant code.",
  "Computers are fast; programmers keep them slow.",
  "The only way to learn a new programming language is by writing programs in it.",
  "In order to be irreplaceable, one must always be different.",
  "The best way to predict the future is to invent it.",
  "Code never lies, comments sometimes do.",
  "Make it work, make it right, make it fast.",
  "If debugging is the process of removing software bugs, then programming must be the process of putting them in.",
  "There is no place like 127.0.0.1.",
  "The best code is no code at all.",
  "A good programmer is someone who always looks both ways before crossing a one-way street.",
  "It’s not a bug — it’s an undocumented feature.",
  "To iterate is human, to recurse divine.",
  "The sooner you start to code, the longer the program will take.",
  "Code is poetry.",
  "Simplicity is prerequisite for reliability.",
  "Don’t let the perfect be the enemy of the good.",
  "Everything is figureoutable.",
  "Stay curious, stay learning.",
  "Your future is created by what you do today, not tomorrow.",
  "Every expert was once a beginner.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Be stronger than your excuses.",
  "Small progress is still progress.",
  "Done is better than perfect.",
  "Dream it, then build it.",
  "Start where you are, use what you have, do what you can.",
  "Keep pushing, even when it’s hard.",
  "Success is not built on success, it’s built on failure and persistence.",
  "Never stop learning — technology won’t.",
  "Trust the process, improve every day.",
  "Don’t count the days. Make the days count.",
  "You are one commit away from success.",
  "The best way to get started is to quit talking and begin doing.",
  "Learning to code is learning to create and to think.",
  "You are capable of amazing things.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Think twice, code once.",
  "Stay focused and keep shipping.",
  "Eat, sleep, code, repeat.",
  "Push your limits, not your luck.",
  "The key to success is consistency.",
  "Fail fast, learn faster.",
  "Ideas are easy. Execution is everything.",
  "A little progress each day adds up to big results.",
  "Keep calm and code on.",
  "Don’t be afraid to start over. It’s a chance to build something better.",
  "Discipline beats motivation.",
  "Turn coffee into code ☕.",
  "Coding is not just code, it’s your art.",
  "Be proud of how far you’ve come.",
  "Logic will get you from A to B. Imagination will take you everywhere.",
  "Don’t watch the clock; do what it does — keep going.",
  "Think it. Build it. Fix it. Improve it.",
  "A bug is just an opportunity to learn.",
  "Don’t compare your chapter 1 to someone else’s chapter 20.",
  "Read the error message — it’s trying to help.",
  "Every line of code you write teaches you something.",
  "Sometimes later becomes never — do it now.",
  "Consistency turns dreams into reality.",
  "Learning never exhausts the mind.",
  "Debugging is like being the detective in a crime movie where you are also the murderer.",
  "Code more, worry less.",
  "Don’t give up — great things take time.",
  "Keep improving one line at a time.",
  "If opportunity doesn’t knock, build a door.",
  "Great things never come from comfort zones.",
  "Focus on progress, not perfection.",
  "Challenge yourself — growth lives there.",
  "Your code reflects your mindset — stay clear.",
  "When nothing goes right, go left (and debug).",
  "Coding is 10% writing and 90% fixing what you wrote.",
  "Even the best programmers were beginners once.",
  "Failure is feedback — adjust and move forward.",
  "Stay humble, stay hungry.",
  "Be the reason someone learns to code.",
  "Patience is key — even for compilers.",
  "Think logically, code creatively.",
  "Every bug fixed is a lesson learned.",
  "Software evolves — so should you.",
  "Refactor not to change behavior, but to reveal it.",
  "Keep building, even when no one’s watching.",
  "Don’t wish for it, work for it.",
  "Learn, unlearn, relearn.",
  "Progress, not perfection.",
  "Every day is a chance to become better.",
  "Failure is just success in progress.",
  "Dream big, start small, act now.",
  "Don’t let fear of bugs stop you from coding.",
  "Stay inspired, stay coding."
];

const currentDay = new Date();
  const index = currentDay.getDate() % quotes.length;

  quoteText.textContent = quotes[index];
});